name: delta-ci-cd

on:
  pull_request:
    branches:
      - main
      - develop

env:
  HUSKY: 0

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: yarn install

      - name: lint source files
        run: yarn lint

      - name: lint styles files
        run: yarn lint-styles

      - name: verify format files
        run: yarn prettier . --check

      - name: build project
        run: yarn build

      - name: upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
